name = "container-trader"
main = "porteiro.js" # O gerente agora é o arquivo JS
compatibility_date = "2024-05-02"

[[containers]]
name = "trader-bot"
image = "Dockerfile" # O Python roda aqui dentro
class_name = "beta"

[durable_objects]
bindings = [{name = "MY_CONTAINER", class_name = "MyContainer"}]

[[migrations]]
tag = "v1"
new_classes = ["MyContainer"]

[triggers]
crons = ["* * * * *"] # Cutuca o porteiro a cada minuto para ele nunca dormir