name = "container-trader"
main = "orquestrador_setup_campeao1.py"
compatibility_date = "2024-05-02"

[[containers]]
name = "trader-bot"
image = "Dockerfile"
class_name = "beta"

# Adicione estas linhas para forçar o container a ficar vivo
[durable_objects]
bindings = [{name = "MY_CONTAINER", class_name = "MyContainer"}]

[[migrations]]
tag = "v1"
new_classes = ["MyContainer"]
[triggers]
crons = ["* * * * *"] # Executa a cada 1 minuto para manter o container acordado