name = "container-trader"
main = "orquestrador_setup_campeao1.py"
compatibility_date = "2024-05-02"

# Isso avisa a Cloudflare para ignorar comandos de build externos
[build]
command = ""

[[containers]]
name = "trader-bot"
image = "Dockerfile"
class_name = "beta"